version: "3.9"

services:
  copyai:
    build:
      context: app/
      dockerfile: Dockerfile
    container_name: copyai
    command: uvicorn main:app --host 0.0.0.0 --port 777
    env_file:
      - .env
    ports:
      - 777:777
    volumes: 
      - ./error_screenshots:/error_screenshots

  mitmproxy:
    build:
      context: mitmproxy/
      dockerfile: Dockerfile
    container_name: mitmproxy
    command: mitmdump -p 8080 -s mitm-injector.py -q
    ports:
      - 8080:8080